# Generated by Django 5.0.6 on 2024-06-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(upload_to='Books/pdfs/'),
        ),
    ]
